# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main CI - Backend

on:
  push:
    branches:
      - "*"
    paths:
    - 'simple-chat-back/**'

jobs:
  # Backend CI
  Backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # services:
    #   localhost:
    #     image: mongo:4.2
    #     ports:
    #       - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: simple-chat-back
        run: npm install

      - name: Running lint
        working-directory: simple-chat-back
        run: npm run lint

      # - name: Running prod build
        # working-directory: simple-chat-back
        # run: npm run build:prod
